module.exports = {
  title: 'Convertiv Design System',
  client: 'Convertiv',
  google_tag_manager: null,
  favicon: '/favicon.ico',
  logo: '/logo.svg',
  poweredBy: true,
  show_components: {
    alert: 'Alert',
    button: 'Button',
    checkbox:'Checkbox',
    input:'Input',
    modal:'Modal',
    pagination: null,
    radio:'Radio',
    select:'Select',
    switch:'Switch',
    tooltip: 'Tooltip',
  },
  type_sort: [
    'Heading 1',
    'Heading 2',
    'Heading 3',
    'Heading 4',
    'Heading 5',
    'Heading 6',
    'Paragraph',
    'Subheading',
    'Blockquote',
    'Input Labels',
    'Link',
  ],
  type_copy: 'Almost before we knew it, we had left the ground.',
  color_sort: ['primary', 'secondary', 'extra', 'system'],
  component_sort: ['primary', 'secondary', 'transparent'],
  
};
