import fs from 'fs-extra';
import path from 'path';

/**
 * Canonical artifact resolution for the workspace-mode docs read API.
 *
 * Logical artifact paths (e.g. `component/badge-primary.html`, `pattern/hero.html`,
 * `component/main.css`) map onto files generated by the build under the app's mirrored
 * `public/api` directory. This module owns the single safe mapping from a logical path to a file
 * on disk: it rejects traversal/malformed paths up front, resolves the content type by extension,
 * and never escapes the generated artifact root.
 *
 * Server-only: imported exclusively by API route handlers.
 */

/** Outcome of validating a logical artifact path segment list. */
export interface ArtifactPathValidation {
  ok: boolean;
  /** Decoded, safe path segments when `ok`; empty otherwise. */
  segments: string[];
  /** Human-readable rejection reason when not `ok`. */
  reason?: string;
}

/**
 * Content type served for an artifact, keyed by file extension.
 * A stored content type would win when present; in workspace mode the extension is authoritative.
 */
const CONTENT_TYPE_BY_EXT: Record<string, string> = {
  '.json': 'application/json',
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
};

const DEFAULT_CONTENT_TYPE = 'text/plain; charset=utf-8';

/** Resolve the content type for an artifact path by its extension, defaulting to text/plain. */
export const contentTypeForArtifactPath = (artifactPath: string): string => {
  const ext = path.extname(artifactPath).toLowerCase();
  return CONTENT_TYPE_BY_EXT[ext] ?? DEFAULT_CONTENT_TYPE;
};

/** Whether a single decoded path segment is structurally safe (no traversal, no separators). */
const isSafeSegment = (segment: string): boolean =>
  segment.length > 0 && segment !== '.' && segment !== '..' && !segment.includes('/') && !segment.includes('\\');

/**
 * Validate the catch-all `artifactPath` segments coming from the route. Rejects:
 * zero segments; any segment that is empty / `.` / `..` / contains a path separator — checked both
 * raw and after `decodeURIComponent` (so encoded `%2E%2E` is rejected too); or any segment that
 * fails to decode.
 */
export const validateArtifactSegments = (rawSegments: string[] | undefined): ArtifactPathValidation => {
  if (!rawSegments || rawSegments.length === 0) {
    return { ok: false, segments: [], reason: 'Artifact path has no segments.' };
  }

  const decoded: string[] = [];
  for (const raw of rawSegments) {
    if (!isSafeSegment(raw)) {
      return { ok: false, segments: [], reason: `Unsafe artifact path segment "${raw}".` };
    }
    let decodedSegment: string;
    try {
      decodedSegment = decodeURIComponent(raw);
    } catch {
      return { ok: false, segments: [], reason: `Artifact path segment "${raw}" could not be decoded.` };
    }
    if (!isSafeSegment(decodedSegment)) {
      return { ok: false, segments: [], reason: `Unsafe artifact path segment "${raw}".` };
    }
    decoded.push(decodedSegment);
  }

  return { ok: true, segments: decoded };
};

/**
 * Absolute path of the generated artifact root (`public/api`) for the running app. Artifacts are
 * mirrored into the app's own public directory by the build (`syncPublicFiles`), so the app reads
 * them from its module-local `.handoff/{projectId}/public/api` — the same location the rest of the
 * app already reads `components.json`/`patterns.json` from.
 */
export const getArtifactRoot = (): string =>
  path.resolve(
    process.env.HANDOFF_MODULE_PATH ?? '',
    '.handoff',
    process.env.HANDOFF_PROJECT_ID ?? '',
    'public',
    'api'
  );

/** A resolved artifact ready to serve. */
export interface ResolvedArtifact {
  absolutePath: string;
  contentType: string;
}

/**
 * Resolve already-validated logical artifact segments to a readable file under the artifact root,
 * or `null` when the artifact does not exist. The resolved path is re-checked to be contained
 * within the root as defense in depth, even though segments are pre-validated.
 */
export const resolveArtifactFile = (segments: string[]): ResolvedArtifact | null => {
  const root = getArtifactRoot();
  const absolutePath = path.resolve(root, ...segments);
  const relative = path.relative(root, absolutePath);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    return null;
  }
  if (!fs.existsSync(absolutePath) || !fs.statSync(absolutePath).isFile()) {
    return null;
  }
  return { absolutePath, contentType: contentTypeForArtifactPath(absolutePath) };
};
